---
title: "Client Report - Can You Predict That?"
subtitle: "Course DS 250"
author: "Saylor Tippetts"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
from lets_plot import *
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html
import pandas as pd

url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv" 
df = pd.read_csv(url)


```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_Clients only care about few things when it comes to actually buying a house! Clients mostly care about having a one story home!_

## QUESTION|TASK 1

__Create 2-3 charts that evaluate potential relationships between the home variables and `before1980`.__ Explain what you learn from the charts that could help a machine learning algorithm. 

_These charts simply give more insight into the data that we are looking at. _

```{python}
from plotnine import *

(ggplot(df, aes(x='factor(before1980)', y='livearea')) +
    geom_boxplot() +
    labs(title="Live Area by Before 1980", x="Before 1980", y="Live Area (sqft)") +
    theme_minimal())


```
```{python}
( ggplot(df, aes(x='yrbuilt')) +
    geom_histogram() +
    labs(title="Year Built Distribution", x="Year Built", y="Count") +
    theme_minimal())

```

```{python}
( ggplot(df, aes(x='factor(before1980)', fill='factor(gartype_Det)')) +
    geom_bar(position='dodge') +
    labs(title="Detached Garage Presence by Before 1980", x="Before 1980", y="Count", fill="Detached Garage") +
    theme_minimal())

```

## QUESTION|TASK 2

__Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Explain your final model choice (algorithm, tuning parameters, etc) and describe what other models you tried.  

_I used the Random Forest Classifier and set my estimator to 200. I ended up getting 90% accuracy._

```{python}
df = df.drop(columns=['parcel', 'yrbuilt'])

X = df.drop(columns=['before1980'])
y = df['before1980']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

rf = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print(" Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))




```


## QUESTION|TASK 3

__Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a feature importance chart and a description of the features. 

_For this, I did a simple Bar Chart ro showase the 10 most important features._

```{python}
importances = pd.Series(rf.feature_importances_, index=X.columns)

# 2. Convert to DataFrame and keep top 10
importance_df = importances.nlargest(10).reset_index()
importance_df.columns = ['feature', 'importance']


(
    ggplot(importance_df, aes(x='feature', y='importance')) +
    geom_col(fill="#69b3a2") +
    labs(title='Top 10 Feature Importances (Random Forest)',
         x='Feature',
         y='Importance Score'))
```


## QUESTION|TASK 4

__Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to interpret each of the evaluation metrics you use.  

_For this, I decided to important the accuracy score and classification report. These just tell more details about small things within the test._

```{python}
# Include and execute your code here
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

```

---

## STRETCH QUESTION|TASK 1

__Repeat the classification model using 3 different algorithms.__ Display their Feature Importance, and Decision Matrix. Explian the differences between the models and which one you would recommend to the Client.   

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 2

__Join the `dwellings_neighborhoods_ml.csv` data to the `dwelling_ml.csv` on the `parcel` column to create a new dataset. Duplicate the code for the stretch question above and update it to use this data.__ Explain the differences and if this changes the model you recomend to the Client.   

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 3

__Can you build a model that predicts the year a house was built?__ Explain the model and the evaluation metrics you would use to determine if the model is good.  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---
